[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
base = "light"
primaryColor = "#3b8bba"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"
